_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 55
                - 105
            "2":
                - 55
                - 105
            "3":
                - 2
                - 13
                - 15
                - 18
                - 19
                - 23
                - 55
                - 61
                - 62
            "4": 3.10.10
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
author:
    value: ML Team
data:
    value:
        augmentation: true
        dataset: CIFAR-10
description:
    value: Testing migration patterns
model:
    value:
        architecture: ResNet50
        dropout: 0.2
        num_layers: 50
training:
    value:
        batch_size: 32
        learning_rate: 0.001
        optimizer: AdamW
version:
    value: 1.0.0
